server-web:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www
    - ./config/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: nmcteam/php56
  volumes:
    - ./config/php/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
